:PROPERTIES:
:ID:       a2ec40d1-1895-4431-9c94-148af35774ee
:ROAM_REFS: https://www.youtube.com/watch?v=LFKZLXVO-Dg
:END:
#+title:  Introduction to Graph Theory: A Computer Science Perspective - YouTube
#+filetags: :Mathematics: :Computer_Science: :Graph_Theory: :Reducible_Youtube:

* Definition of A Graph

A graph $G = (V, E)$ is a set of vertices $V$ and edges $E$ where each $(u, v)$ is a connection between vertices. $u, v \in V$
 Vertices and nodes are used interchangebly.

* Terminology

** Neighbors

    Two vertices are neighbors if an edge connects them.
vertices $u$ and $v$ are neighbors if an edge $(u, v)$ connects them.

** Degree

 Degree - degree$(v)$ is equal to the number of edges connected to $v$

** Path

Sequence of vertices connected by edges

*** path length

number of edges in a path

*** cycle

path that starts and ends at the same vertex

** Connectivity

two vertices are connected if a path exists between them.

A graph is connected when all vertices are connected.

*** Connected component

A subset of vertices  $V_{i} \subseteq V$ that is connected

* Types of Graphs
** Undirected graph

Edges don't have a direction

** Directed graph

Edges are unidirectional

** Cyclic vs Acyclic graph

A graph with cycles is called cyclic

A graph without cycles is called acyclic

** Weighted graph

A graph where edges are weighted

** Trees

1. Trees are connected and acyclical graphs
2.  Removing an edge disconnects the graph
3. Adding an edge creates a cycle

* Graph Representations

** Adjacency matrix

\begin{equation}
A_{ij} = \begin{cases}
1, & \text{for edge $(i,j)$}\\
0, & \text{otherwise}
\end{cases}
\end{equation}

Each edge creates 2 entries because the graph is undirected.

** Edge Set


** Adjacency List

Each node gets a list of other nodes it is connected to.
This is common because it is memory efficient

* Personal Summary
Graph Theory is a useful tool for modeling many computer science problems. Graphs are edges and vertices (nodes). Its useful for modeling many problems, Some that come to mind are the Directed Acyclical nature of personal identity and git.
